"""initial_schema

Revision ID: 39863728b93d
Revises:
Create Date: 2026-08-04 00:21:18.273927
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39863728b93d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_student_no'), 'users', ['student_no'], unique=True)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_invite_code'), 'classes', ['invite_code'], unique=True)
    op.create_index(op.f('ix_classes_teacher_id'), 'classes', ['teacher_id'], unique=False)
    op.create_table('topic_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_banks_teacher_id'), 'topic_banks', ['teacher_id'], unique=False)
    op.create_table('class_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_class_student')
    )
    op.create_index(op.f('ix_class_members_class_id'), 'class_members', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_members_student_id'), 'class_members', ['student_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty', native_enum=False), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['topic_banks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topics_bank_active', 'topics', ['bank_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_topics_bank_id'), 'topics', ['bank_id'], unique=False)
    op.create_index(op.f('ix_topics_category'), 'topics', ['category'], unique=False)
    op.create_index(op.f('ix_topics_difficulty'), 'topics', ['difficulty'], unique=False)
    op.create_table('training_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('topic_bank_id', sa.Integer(), nullable=False),
    sa.Column('preparation_seconds', sa.Integer(), nullable=False),
    sa.Column('speaking_seconds', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redraw_limit', sa.Integer(), nullable=False),
    sa.Column('rerecord_limit', sa.Integer(), nullable=False),
    sa.Column('notes_required', sa.Boolean(), nullable=False),
    sa.Column('allow_early_finish', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('preparation_seconds > 0', name='ck_task_preparation_positive'),
    sa.CheckConstraint('speaking_seconds > 0', name='ck_task_speaking_positive'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_bank_id'], ['topic_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_class_status', 'training_tasks', ['class_id', 'status'], unique=False)
    op.create_index(op.f('ix_training_tasks_class_id'), 'training_tasks', ['class_id'], unique=False)
    op.create_index(op.f('ix_training_tasks_due_at'), 'training_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_training_tasks_starts_at'), 'training_tasks', ['starts_at'], unique=False)
    op.create_index(op.f('ix_training_tasks_status'), 'training_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_training_tasks_teacher_id'), 'training_tasks', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_training_tasks_topic_bank_id'), 'training_tasks', ['topic_bank_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('final_topic_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Enum('DRAWING', 'PREPARING', 'SPEAKING', 'REVIEW', 'SUBMITTED', name='sessionphase', native_enum=False), nullable=False),
    sa.Column('preparation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preparation_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speaking_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speaking_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speaking_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_attempts_started', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('self_assessment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['final_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['training_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'student_id', name='uq_task_student_session')
    )
    op.create_index('ix_sessions_task_phase', 'training_sessions', ['task_id', 'phase'], unique=False)
    op.create_index(op.f('ix_training_sessions_phase'), 'training_sessions', ['phase'], unique=False)
    op.create_index(op.f('ix_training_sessions_student_id'), 'training_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_submitted_at'), 'training_sessions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_training_sessions_task_id'), 'training_sessions', ['task_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('content_accuracy', sa.Integer(), nullable=False),
    sa.Column('logical_structure', sa.Integer(), nullable=False),
    sa.Column('fluency', sa.Integer(), nullable=False),
    sa.Column('vocabulary', sa.Integer(), nullable=False),
    sa.Column('time_control', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('content_accuracy BETWEEN 0 AND 20', name='ck_eval_content'),
    sa.CheckConstraint('fluency BETWEEN 0 AND 20', name='ck_eval_fluency'),
    sa.CheckConstraint('logical_structure BETWEEN 0 AND 20', name='ck_eval_logic'),
    sa.CheckConstraint('time_control BETWEEN 0 AND 20', name='ck_eval_time'),
    sa.CheckConstraint('vocabulary BETWEEN 0 AND 20', name='ck_eval_vocabulary'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_session_id'), 'evaluations', ['session_id'], unique=True)
    op.create_index(op.f('ix_evaluations_teacher_id'), 'evaluations', ['teacher_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'attempt_number', name='uq_recording_attempt')
    )
    op.create_index(op.f('ix_recordings_session_id'), 'recordings', ['session_id'], unique=False)
    op.create_table('topic_draw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'draw_number', name='uq_session_draw_number')
    )
    op.create_index(op.f('ix_topic_draw_records_session_id'), 'topic_draw_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_topic_draw_records_topic_id'), 'topic_draw_records', ['topic_id'], unique=False)
    op.create_table('training_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_notes_session_id'), 'training_notes', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_notes_session_id'), table_name='training_notes')
    op.drop_table('training_notes')
    op.drop_index(op.f('ix_topic_draw_records_topic_id'), table_name='topic_draw_records')
    op.drop_index(op.f('ix_topic_draw_records_session_id'), table_name='topic_draw_records')
    op.drop_table('topic_draw_records')
    op.drop_index(op.f('ix_recordings_session_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_evaluations_teacher_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_session_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_training_sessions_task_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_submitted_at'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_student_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_phase'), table_name='training_sessions')
    op.drop_index('ix_sessions_task_phase', table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_training_tasks_topic_bank_id'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_teacher_id'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_status'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_starts_at'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_due_at'), table_name='training_tasks')
    op.drop_index(op.f('ix_training_tasks_class_id'), table_name='training_tasks')
    op.drop_index('ix_tasks_class_status', table_name='training_tasks')
    op.drop_table('training_tasks')
    op.drop_index(op.f('ix_topics_difficulty'), table_name='topics')
    op.drop_index(op.f('ix_topics_category'), table_name='topics')
    op.drop_index(op.f('ix_topics_bank_id'), table_name='topics')
    op.drop_index('ix_topics_bank_active', table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_class_members_student_id'), table_name='class_members')
    op.drop_index(op.f('ix_class_members_class_id'), table_name='class_members')
    op.drop_table('class_members')
    op.drop_index(op.f('ix_topic_banks_teacher_id'), table_name='topic_banks')
    op.drop_table('topic_banks')
    op.drop_index(op.f('ix_classes_teacher_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_invite_code'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_users_student_no'), table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
